# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
