# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170419_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='blood',
        ),
        migrations.RemoveField(
            model_name='users',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
    ]
