# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170629_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
