# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170714_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
